messages:
  vipExpired: "seu vip %vip% expirou, acesso nossa loja e compre mais dias."
  vipRemoved: "seu vip %vip% foi removido por um staff"


permissions:
  - 'guardianvips.addvip'
  - 'guardianvips.addtimevip'
  - 'guardianvips.key.generate'
  - 'guardianvips.key.list'
  - 'guardianvips.removevip'
  - 'guardianvips.removevip'
  - 'guardianvips.removevip'
  - 'guardianvips.reload'
  - 'guardianvips.showvips'

defaultWorld: "world"
storage:
  user: 'root'
  pass: '123'
  host: 'localhost'
  db: 'dev'