permissions:
  - 'guardianvips.admin.help'
  - 'guardianvips.key.generate'
  - 'guardianvips.removekeyvip'
  - 'guardianvips.key.list'
  - 'guardianvips.addvip'
  - 'guardianvips.setvip'
  - 'guardianvips.removevip'
  - 'guardianvips.showvips'
  - 'guardianvips.listvips'
  - 'guardianvips.addtimevip'
  - 'guardianvips.admin'

## In Hours
intervalNotifiVipEnding: 24
minDyasToNotify: 1
storage:
  type: "SQLite"
  user: 'root'
  pass: '123'
  host: 'localhost'
  db: 'dev'