messages:
  vipExpired: "seu vip %vip% expirou, acesso nossa loja e compre mais dias."
  vipRemoved: "seu vip %vip% foi removido por um staff"

storage:
  user: 'mysql'
  pass: '123'
  host: 'localhost'
  db: 'plugins'
  port: 3306