messages:
  vipExpired: "seu vip %vip% expirou, acesso nossa loja e compre mais dias."
  vipRemoved: "seu vip %vip% foi removido por um staff"


# Tipo de chave de ativacao
# 1 - Apenas numeros
# 2 - Apenas letras
keyType: 1

defaultWorld: "world"
storage:
  user: 'root'
  pass: '123'
  host: 'localhost'
  db: 'dev'