name: GuardianVIPS
version: 1.0
main: guardianVip.GuardianVips

commands:
  guardianvip:
    aliases: "gvips"
  gerarkeyvip:
  enviarkeyvip:
  listarkeysvip:
  removerkeyvip:
  ativarvip:
    aliases:
      - "usekey"
      - "usarkey"
  darvip:
  setvip:
  removervip:
  tempovip:
    aliases:
      - "viptime"
  listvip:
  removeviptime:
  addTempovipglobal: